#!/usr/bin/python
import glob,os

print "Content-Type: text/html\n"
print "<html>"
print "<title>FAST Single Pulses</title>"
#print "<meta http-equiv='refresh' content='10'>"
print "<h2> Beams with the most number of detections:</h2>"

pngs = glob.glob('*.png')

for png in pngs:
    print png
    info = """
    <figure>
        <img src="../%s"   height="200">
    </figure>
    """ % png
    print info

print "Hello world"

print "</html>"
